name: mars
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.1.0
  - absl-py=0.10.0
  - aiohttp=3.6.3
  - astor=0.8.1
  - async-timeout=3.0.1
  - attrs=20.2.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.20.1
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.1.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - dill=0.3.2
  - freetype=2.10.4
  - gast=0.2.2
  - giflib=5.2.1
  - google-auth=1.22.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.8.0
  - hdf5=1.8.20
  - icc_rt=2019.0.0
  - icu=67.1
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - joblib=0.17.0
  - jpeg=9d
  - jxrlib=1.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - lcms2=2.11
  - lerc=2.2
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libiconv=1.15
  - libopencv=3.4.2
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxgboost=0.90
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - multidict=4.7.6
  - networkx=2.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - opt_einsum=3.1.0
  - pillow=8.0.1
  - pip=20.2.4
  - progressbar=2.5
  - protobuf=3.13.0.1
  - py-opencv=3.4.2
  - py-xgboost=0.90
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyside2=5.13.2
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.12.9
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.0
  - six=1.15.0
  - sk-video=1.1.10
  - snappy=1.1.8
  - sqlite=3.33.0
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=0.16.1
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.2
  - zfp=0.5.5
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - colour-demosaicing==0.1.5
    - colour-science==0.3.15
    - hmmlearn==0.2.4
prefix: C:\Users\Ann\miniconda3\envs\mars
